[scrolling]
history = 100000

[font]
size = 14.0

[font.bold]
family = "AdwaitaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "AdwaitaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "AdwaitaMono Nerd Font"
style = "Italic"

[font.normal]
family = "AdwaitaMono Nerd Font"
style = "Regular"

[window]
decorations = "full"
padding = { x = 6, y = 4 }

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "On" }

[env]
TERM = "xterm-256color"
