[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "J"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "H"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "H"
mods = "Control|Shift"
